# Generated by Django 4.1.5 on 2023-02-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact_details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(default="", max_length=100)),
                ("Email", models.EmailField(default="", max_length=100)),
                ("Subject", models.CharField(default="", max_length=10)),
                ("message", models.CharField(default="", max_length=550)),
            ],
        ),
    ]
